Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper https://stackoverflow.com/questions/43826718/noclassdeffounderror-of-com-fasterxml-jackson-databind-objectmapper-with-maven